In [2]:
import pandas as pd
import numpy as np

In [3]:
ipl = pd.read_csv(r"C:\Users\shree\Downloads\ipl_deliveries.csv")
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [6]:
ipl.groupby('batter')['total_run'].sum().sort_values(ascending=False)

batter
V Kohli           6876
S Dhawan          6561
DA Warner         6191
RG Sharma         6083
SK Raina          5780
                  ...
SS Cottrell          0
R Sanjay Yadav       0
L Ablish             0
Akash Deep           0
JL Denly             0
Name: total_run, Length: 605, dtype: int64

In [8]:
ipl.groupby('batter')['batsman_run'].sum().sort_values(ascending=False)

batter
V Kohli           6634
S Dhawan          6244
DA Warner         5883
RG Sharma         5881
SK Raina          5536
                  ...
C Nanda              0
Akash Deep           0
S Ladda              0
V Pratap Singh       0
S Lamichhane         0
Name: batsman_run, Length: 605, dtype: int64

In [12]:
ipl.groupby(['batter','ID'])['batsman_run'].sum().groupby('batter').mean().sort_values(ascending=False)

batter
KL Rahul          39.343434
LMP Simmons       37.206897
RM Patidar        36.727273
DA Warner         36.314815
SE Marsh          36.072464
                    ...
Sunny Gupta        0.000000
Akash Deep         0.000000
V Pratap Singh     0.000000
ND Doshi           0.000000
U Kaul             0.000000
Name: batsman_run, Length: 605, dtype: float64

In [13]:
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [16]:
out = ipl[ipl['isWicketDelivery'] == 1]

In [19]:
out.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
23,1312200,Rajasthan RoyalsGujarat Titans,1,3,6,YBK Jaiswal,Yash Dayal,JC Buttler,NaN,0,0,0,0,1,YBK Jaiswal,caught,R Sai Kishore,Rajasthan Royals,Gujarat Titans
49,1312200,Rajasthan RoyalsGujarat Titans,1,8,2,SV Samson,HH Pandya,JC Buttler,NaN,0,0,0,0,1,SV Samson,caught,R Sai Kishore,Rajasthan Royals,Gujarat Titans
70,1312200,Rajasthan RoyalsGujarat Titans,1,11,5,D Padikkal,Rashid Khan,JC Buttler,NaN,0,0,0,0,1,D Padikkal,caught,Mohammed Shami,Rajasthan Royals,Gujarat Titans
72,1312200,Rajasthan RoyalsGujarat Titans,1,12,1,JC Buttler,HH Pandya,SO Hetmyer,NaN,0,0,0,0,1,JC Buttler,caught,WP Saha,Rajasthan Royals,Gujarat Titans
89,1312200,Rajasthan RoyalsGujarat Titans,1,14,6,SO Hetmyer,HH Pandya,R Ashwin,NaN,0,0,0,0,1,SO Hetmyer,caught and bowled,NaN,Rajasthan Royals,Gujarat Titans

In [18]:
out.groupby('bowler')['bowler'].count().sort_values(ascending=False)

bowler
DJ Bravo            207
SL Malinga          188
A Mishra            175
R Ashwin            174
YS Chahal           172
                   ...
PM Sarvesh Kumar      1
AC Gilchrist          1
CL White              1
LA Carseldine         1
GH Vihari             1
Name: bowler, Length: 408, dtype: int64

In [20]:
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [22]:
ipl.groupby('bowler')['total_run'].sum().sort_values(ascending=False)

bowler
R Ashwin           4596
DJ Bravo           4436
PP Chawla          4368
RA Jadeja          4114
Harbhajan Singh    4101
                   ...
SN Khan               6
AM Rahane             5
SPD Smith             5
DA Warner             2
AC Gilchrist          0
Name: total_run, Length: 472, dtype: int64

In [24]:
ipl.groupby('BattingTeam')['total_run'].sum().sort_values(ascending=False)

BattingTeam
Mumbai Indians                 36663
Royal Challengers Bangalore    35190
Kolkata Knight Riders          34201
Chennai Super Kings            33393
Kings XI Punjab                30064
Rajasthan Royals               29681
Delhi Daredevils               24296
Sunrisers Hyderabad            23643
Deccan Chargers                11463
Delhi Capitals                 10145
Pune Warriors                   6358
Gujarat Lions                   4862
Punjab Kings                    4493
Gujarat Titans                  2663
Lucknow Super Giants            2548
Rising Pune Supergiant          2470
Rising Pune Supergiants         2063
Kochi Tuskers Kerala            1901
Name: total_run, dtype: int64

In [25]:
out.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
23,1312200,Rajasthan RoyalsGujarat Titans,1,3,6,YBK Jaiswal,Yash Dayal,JC Buttler,NaN,0,0,0,0,1,YBK Jaiswal,caught,R Sai Kishore,Rajasthan Royals,Gujarat Titans
49,1312200,Rajasthan RoyalsGujarat Titans,1,8,2,SV Samson,HH Pandya,JC Buttler,NaN,0,0,0,0,1,SV Samson,caught,R Sai Kishore,Rajasthan Royals,Gujarat Titans
70,1312200,Rajasthan RoyalsGujarat Titans,1,11,5,D Padikkal,Rashid Khan,JC Buttler,NaN,0,0,0,0,1,D Padikkal,caught,Mohammed Shami,Rajasthan Royals,Gujarat Titans
72,1312200,Rajasthan RoyalsGujarat Titans,1,12,1,JC Buttler,HH Pandya,SO Hetmyer,NaN,0,0,0,0,1,JC Buttler,caught,WP Saha,Rajasthan Royals,Gujarat Titans
89,1312200,Rajasthan RoyalsGujarat Titans,1,14,6,SO Hetmyer,HH Pandya,R Ashwin,NaN,0,0,0,0,1,SO Hetmyer,caught and bowled,NaN,Rajasthan Royals,Gujarat Titans

In [27]:
out.groupby('BowlingTeam')['ID'].count().sort_values(ascending=False)

BowlingTeam
Mumbai Indians                 1411
Royal Challengers Bangalore    1311
Chennai Super Kings            1290
Kolkata Knight Riders          1275
Rajasthan Royals               1095
Kings XI Punjab                1076
Sunrisers Hyderabad             915
Delhi Daredevils                912
Deccan Chargers                 446
Delhi Capitals                  405
Pune Warriors                   238
Punjab Kings                    162
Gujarat Lions                   151
Rising Pune Supergiant          113
Gujarat Titans                  101
Lucknow Super Giants            100
Rising Pune Supergiants          76
Kochi Tuskers Kerala             74
Name: ID, dtype: int64

In [31]:
ipl.groupby(['BattingTeam','overs'])['total_run'].sum().groupby('BattingTeam').mean()

BattingTeam
Chennai Super Kings            1669.65
Deccan Chargers                 573.15
Delhi Capitals                  507.25
Delhi Daredevils               1214.80
Gujarat Lions                   243.10
Gujarat Titans                  133.15
Kings XI Punjab                1503.20
Kochi Tuskers Kerala             95.05
Kolkata Knight Riders          1710.05
Lucknow Super Giants            127.40
Mumbai Indians                 1833.15
Pune Warriors                   317.90
Punjab Kings                    224.65
Rajasthan Royals               1484.05
Rising Pune Supergiant          123.50
Rising Pune Supergiants         103.15
Royal Challengers Bangalore    1759.50
Sunrisers Hyderabad            1182.15
Name: total_run, dtype: float64

In [32]:
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [35]:
ipl['Batting_Pair'] = ipl.apply(lambda row: tuple(sorted([row['batter'],row['non-striker']])),axis=1)
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,Batting_Pair
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"

In [37]:
ipl.groupby('Batting_Pair')['total_run'].sum().sort_values(ascending=False)

Batting_Pair
(AB de Villiers, V Kohli)            3134
(CH Gayle, V Kohli)                  2802
(DA Warner, S Dhawan)                2357
(G Gambhir, RV Uthappa)              1906
(KL Rahul, MA Agarwal)               1731
                                     ...
(AD Mascarenhas, Gurkeerat Singh)       0
(NLTC Perera, RV Gomez)                 0
(Iqbal Abdulla, TS Mills)               0
(NM Coulter-Nile, SV Samson)            0
(Kartik Tyagi, Shashank Singh)          0
Name: total_run, Length: 4259, dtype: int64